### ISSUE TITLE
Two birds, one stone. Tutorial on how to implement a feature & implement gacha.

### ISSUE THREAD

**Issue by yuvlian** [LEAGUE-OF-NINE/FurinaLC#6]
We want people to understand the project structure. So, for the tutorial let's try implementing gacha properly.

- [x] Implement gacha
  - [x] Add handler for route /api/PlayGacha
  - [x] Parse static data resource for gacha
  - [x] Make rng system
  - [ ] Implement DB to store pity points & shards
  - [ ] Upload tutorial video

**Comment by Galeilian** [comment]
is it normal to not being able to play mirror dungeon / RR?

**Comment by yuvlian** [comment]
> is it normal to not being able to play mirror dungeon / RR?

Yes. Please read FAQ next time. I made it for a reason.

**Comment by yuvlian** [comment]
Let's just skip the last two tasks, I cba
